environment: default
imgix:
  header_jpg: "?ch=Width&fit=max&fm=jpg&auto=format&lossless=true"
  header_png: "?ch=Width&fit=max&fm=png&auto=format&lossless=1"
  header_gif: "?ch=Width,Save-Data&fm=gif"
  jpg: "?fm=jpg&auto=format&lossless=true"
  png: "?fm=png&auto=format&lossless=1"
  gif: ""

code_languages:

  # curl: 
  #   name: curl
  #   extension: sh
  # python: 
  #   name: python
  #   extension: py
  # nodejs: 
  #   name: nodejs
  #   extension: js
  # ruby: 
  #   name: ruby
  #   extension: rb
  # java: 
  #   name: java
  #   extension: java
  # go: 
  #   name: go
  #   extension: go
  # csharp:
  #   name: csharp
  #   extension: cs
  # cplusplus:
  #   name: C++
  #   extension: cpp


  'py':
    extension: py
    name: python
  'rb':
    extension: rb
    name: ruby
  'sh':
    extension: sh
    name: curl
  'sh':
    extension: sh
    name: curl
  'go':
    extension: go
    name: go
  'java':
    extension: java
    name: java
  'cs':
    extension: cs
    name: csharp
  'php':
    extension: php
    name: php


# code_languages:
#   - name: Curl
#     ext: curl
#   - name: Curl
#     ext: sh
#   - name: Python
#     ext: py
#   - name: Ruby
#     ext: rb
#   - name: PHP
#     ext: php
#   - name: Go
#     ext: go
#   - name: Csharp
#     ext: csharp
#   - name: Java
#     ext: java
  


    
branch: ""

header_scripts:
  - hotjar: false
  - google-tag-manager: false
  - google-site-tag: false
  - marketo: false
  - quora-pixel: false

footer_scripts:
  - snowplow: false
  - adroll: false

# Docs allowed regions for redirecting
allowedRegions: 
  - name: US
    value: us
  - name: EU
    value: eu 